-- PostgreSQL schema definitions for storing CI/CD metrics
-- extracted via GHAminer (e.g., builds, commits, durations).

-- Role: Metrics & KPIs
CREATE TABLE builds (
    id_build BIGINT PRIMARY KEY,
    repo TEXT,
    branch TEXT,
    commit_sha TEXT,
    languages TEXT,
    status TEXT,
    conclusion TEXT,
    workflow_event_trigger TEXT,
    issuer_name TEXT,
    workflow_id BIGINT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    build_duration DOUBLE PRECISION,
    total_builds INTEGER,
    gh_files_added INTEGER,
    gh_files_deleted INTEGER,
    gh_files_modified INTEGER,
    tests_ran BOOLEAN,
    gh_lines_added INTEGER,
    gh_lines_deleted INTEGER,
    file_types TEXT,
    gh_tests_added INTEGER,
    gh_tests_deleted INTEGER,
    gh_test_churn DOUBLE PRECISION,
    gh_src_churn DOUBLE PRECISION,
    gh_pull_req_number INTEGER,
    gh_is_pr BOOLEAN,
    gh_sloc INTEGER,
    gh_description_complexity DOUBLE PRECISION,
    gh_src_files INTEGER,
    gh_doc_files INTEGER,
    gh_other_files INTEGER,
    git_num_committers INTEGER,
    gh_job_id TEXT,
    total_jobs INTEGER,
    gh_first_commit_created_at TIMESTAMPTZ,
    gh_team_size_last_3_month INTEGER,
    gh_commits_on_files_touched INTEGER,
    gh_num_pr_comments INTEGER,
    git_merged_with TEXT,
    gh_test_lines_per_kloc DOUBLE PRECISION,
    build_language TEXT,
    dependencies_count INTEGER,
    workflow_size INTEGER,
    test_framework TEXT,
    tests_passed INTEGER,
    tests_failed INTEGER,
    tests_skipped INTEGER,
    tests_total INTEGER,
    workflow_name TEXT,
    dockerfile_changed INTEGER,
    docker_compose_changed INTEGER,
    fetch_duration DOUBLE PRECISION
);